name: Windows Calculator Continuous Integration Pipeline
on:
  push:
    branches: [main, release/**, feature/**]
  pull_request:
    branches: [main, release/**, feature/**]
  workflow_dispatch:
    inputs:
jobs:
  buildWinCalc:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        include:
        - platform: x64
        - platform: x86
          if: ${{ github.event_name != 'pull_request' }}
    steps:
    - uses: actions/checkout@v4
    - uses: nuget/setup-nuget@v2
      name: Use NuGet 6.x
      with:
        nuget-version: '6.x'
    - run: nuget restore ./src/Calculator.sln
    - run: |
        $hashedRunId = ${{ github.run_id }} % 0x7fffffff
        $version = "0.$hashedRunId.${{ github.run_number }}.${{ github.run_attempt }}"
        echo $version
        ./build/scripts/UpdateAppxManifestVersion.ps1 `
          -AppxManifest ./src/Calculator/Package.appxmanifest `
          -Version $version
      shell: pwsh
      name: Set version number in AppxManifest
    - uses: microsoft/setup-msbuild@v2
      name: Add MSBuild to PATH
    - run: |
        $hashedRunId = ${{ github.run_id }} % 0x7fffffff
        $version = "0.$hashedRunId.${{ github.run_number }}.${{ github.run_attempt }}"
        msbuild ./src/Calculator.sln `
          -bl:./output/${{ matrix.platform }}/Calculator.binlog `
          -p:OutDir=./output/${{ matrix.platform }}/ `
          -p:Platform=${{ matrix.platform }} `
          -p:Configuration=Release `
          -p:GenerateProjectSpecificOutputFolder=true `
          -p:Version=$version `
          -maxCpuCount `
          -t:Publish `
          -p:PublishDir=./output/${{ matrix.platform }}/publish
      shell: pwsh
      name: Build Calculator.sln
#  testCalc:
#    needs: buildWinCalc
#    runs-on: windows-latest
