name: Windows Calculator Continuous Integration Pipeline
on:
  push:
    branches: [main, release/**, feature/**]
  pull_request:
    branches: [main, release/**, feature/**]
  workflow_dispatch:
    inputs:
jobs:
  buildWinCalc:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nuget/setup-nuget@v2
      name: Use NuGet 6.x
      with:
        nuget-version: '6.x'
    - run: nuget restore ./src/Calculator.sln
    - run: |
        $hashedRunId = ${{ github.run_id }} % 0x7fffffff
        $version = "0.$hashedRunId.${{ github.run_number }}.${{ github.run_attempt }}"
        echo $version
        ./build/scripts/UpdateAppxManifestVersion.ps1 `
          -AppxManifest ./src/Calculator/Package.appxmanifest `
          -Version $version
      shell: pwsh
      name: Set version number in AppxManifest
    - run: microsoft/setup-msbuild@v2
      name: Add MSBuild to PATH
    - run: |
        $hashedRunId = ${{ github.run_id }} % 0x7fffffff
        $version = "0.$hashedRunId.${{ github.run_number }}.${{ github.run_attempt }}"
        msbuild ./src/Calculator.sln `
          -bl ./output/x64/Calculator.binlog `
          -p:OutDir=./output/x64/ `
          -p:GenerateProjectSpecificOutputFolder=true `
          -p:Version=$version `
          -t:Publish `
          -p:PublishDir=./output/x64/publish
      shell: pwsh
#  testCalc:
#    needs: buildWinCalc
#    runs-on: windows-latest
