name: Windows Calculator Continuous Integration Pipeline
on:
  push:
    branches: [main, release/**, feature/**]
  pull_request:
    branches: [main, release/**, feature/**]
  workflow_dispatch:
    inputs:
jobs:
  buildWinCalc:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nuget/setup-nuget@v2
      name: Use NuGet 6.x
      with:
        nuget-version: '6.x'
    # - run: nuget restore ./src/Calculator.sln
    - run: |
        ./build/scripts/UpdateAppxManifestVersion.ps1 `
          -AppxManifest ./src/Calculator/Package.appxmanifest `
          -Version 0.${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
      shell: pwsh
      name: Set version number in AppxManifest
#  testCalc:
#    needs: buildWinCalc
#    runs-on: windows-latest
